### ISSUE TITLE
Invalid characters in directory name : <->-vs-react-fragment

### ISSUE THREAD

**Issue by monkeyscript** [phuoc-ng/this-vs-that#197]
The directory **/client/posts/<->-vs-react-fragment** is causing git clone to fail as < and > are considered to be invalid in directory names.

So I suggest renaming it into something like `react-fragment-shorthand-vs-longhand` or `rf-shorthand-vs-rf-longhand`.

**Comment by monkeyscript** [comment]
I would also recommend modifying your `dev-server` script cause `rm -rf` won't work everywhere and I had to run the commands individually.

**Comment by phuoc-ng** [comment]
Just saw that. `react-fragment-shorthand-vs-longhand` is better. Please change it in your recent PR 👍
